added toggle_all_terms() function to toggle all terminals
akinsho/toggleterm.nvim pull request #107
Opened 2021-10-30 04:46 UTC by jorgerojas26

This is useful i think for toggling terminals with just one mapping.

2021-11-01 09:13 UTC, akinsho commented
@jorgerojas26 thanks for the PR, this came up a while ago, and I added a `ToggleTermOpenAll` and a `ToggleTermCloseAll` command in #48 but the issue that came up there that lead to two commands was how to behave it there was one of several terminals opened. Should the toggle close the open one or open all the remaining hidden ones. This approach seems to choose to close the terminal if any is open and re-open all. 

Tbh I don't really mind but I don't want both implementations since it's unnecessary complexity so I'm in favour of choosing your approach, but it would be good to remove the `OpenAll` and `CloseAll` commands and just add a `ToggleTermToggleAll` command. Then add that to the documentation as well so users can find it.

2021-11-10 02:31 UTC, jorgerojas26 commented
Sorry for late response, i have made the changes you requested, please check and tell me if they are ok for merging.

2021-11-11 08:32 UTC, akinsho commented on plugin/toggleterm.vim
> +" command! ToggleTermCloseAll lua require'toggleterm'.toggle_all("close")
@jorgerojas26 I was thinking that this and all the other code related to the old functionality should be deleted not just commented out, can you remove the commented code here and also the function they reference e.g. `toggle_all` should be replaced with your implementation so there is only one function doing this and only one command

2021-11-11 08:33 UTC, akinsho requested changes
@jorgerojas26 thanks for tweaking this, I think what would be best though would be to completely remove the old toggle_all code as mentioned in my comment and replace the implementation of `toggle_all` with `toggle_all_terms`

2021-11-15 19:38 UTC, akinsho commented
Just tested this out and it works nicely 👍🏿 . Thanks for making the changes and contributing 🚀

2021-11-15 19:40 UTC, merged

2023-03-30 14:36 UTC, frt commented
I think it would be nice if the open_mapping mapping did the ToggleTermToggleAll instead of the ToggleTerm. Or if configuration to do this was in the documentation.

2023-03-30 14:50 UTC, akinsho commented
@frt this issue is almost 2 years old so no longer relevant at all. FWIW the most recent commits of the plugin will now open and close the entire terminal view by default, so if you have 2 terminals it will close two and if you open it will open 2. So nothing in this issue relevant anymore.

2023-03-30 16:33 UTC, frt commented
Thank you @akinsho, I was using a tag (v2.2.1) without the most recent commits. After changing the Packer configuration to use one of the last commits of the main branch it is now working like I've expected in my first comment. Thank you.